# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/messages.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/messages.proto\x12\x0c\x63om.ai.proto\"\x9e\x01\n\x07\x43ompany\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontact_info\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x18\n\x10outreach_message\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\x12(\n\x08keywords\x18\x07 \x03(\x0b\x32\x16.com.ai.proto.Keywords\"\x18\n\x08Keywords\x12\x0c\n\x04name\x18\x01 \x01(\t\"Z\n\tAIMessage\x12\x14\n\x0csystemprompt\x18\x01 \x01(\t\x12\x11\n\tuserquery\x18\x02 \x01(\t\x12$\n\x05items\x18\x03 \x03(\x0b\x32\x15.com.ai.proto.Companyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPANY']._serialized_start=39
  _globals['_COMPANY']._serialized_end=197
  _globals['_KEYWORDS']._serialized_start=199
  _globals['_KEYWORDS']._serialized_end=223
  _globals['_AIMESSAGE']._serialized_start=225
  _globals['_AIMESSAGE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
