# Java
JAVA_HOME=""
JAVA_BIN=""
export JAVA_HOME

ANDROID_PLATFORM_TOOLS=""
ANDROID_HOME=""

export ANDROID_HOME

VISUAL_CODE=""

PATH="$VISUAL_CODE:$JAVA_BIN:$JAVA_HOME:$ANDROID_PLATFORM_TOOLS:$PATH"
export PATH
