/*
	Script for creation of trade_company_db
    
    It has 5 tables:
    
    CUSTOMERS, SALES_REPS, OFFICES, PRODUCTS, ORDERS

*/

-- Delete a database if it exists
DROP DATABASE trade_company_db;

-- Create a database
CREATE DATABASE trade_company_db;

-- Select a database to work with
USE trade_company_db;

CREATE TABLE PRODUCTS(
	MFR_ID CHAR(3) NOT NULL,
	PRODUCT_ID CHAR(3) NOT NULL,
	DESCRIPTION VARCHAR(20) NOT NULL, 
	PRICE DECIMAL(10, 2) NOT NULL,
	QTY_ON_HAND INT NOT NULL,
	PRIMARY KEY(MFR_ID, PRODUCT_ID)			
);

CREATE TABLE SALES_REPS( 
	EMPL_NUМ INT NOT NULL, 
	NAME VARCHAR(15) NOT NULL, 
	AGE INT,
	REP_OFFICE INT,
	TITLE VARCHAR(10),
	HIRE_DATE DATE NOT NULL, 
	МANAGER INT,
	QUOTA DECIMAL(10,2),
	SALES DECIMAL(10,2) NOT NULL, 
	PRIMARY KEY (EMPL_NUМ), 
	-- Note that HAS_PERSON_MGR is key name 
	CONSTRAINT HAS_PERSONAL_MGR FOREIGN KEY (МANAGER) REFERENCES SALES_REPS(EMPL_NUМ) ON DELETE SET NULL
);

CREATE TABLE OFFICES(
	OFFICE INT NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	REGION VARCHAR(10) NOT NULL,
	MGR INT,
	TARGET DECIMAL(10, 2),
	SALES DECIMAL(10, 2) NOT NULL,
	PRIMARY KEY (OFFICE),
	-- Note that HAS_OFFICE_MGR is key name 
	CONSTRAINT HAS_OFFICE_MGR FOREIGN KEY (MGR) REFERENCES SALES_REPS(EMPL_NUМ) ON DELETE SET NULL 
);

-- Note that SALES_REPS is key name 
ALTER TABLE SALES_REPS ADD CONSTRAINT WORKS_IN FOREIGN KEY (REP_OFFICE) REFERENCES OFFICES(OFFICE);

CREATE TABLE CUSTOMERS( 
	CUST_NUМ INT NOT NULL, 
	COMPANY VARCHAR(20) NOT NULL, 
	CUST_REP INT,
	CREDIT_LIMIT DECIMAL(10, 2),
	PRIMARY KEY (CUST_NUМ),
	CONSTRAINT PERSONAL_MGR FOREIGN KEY (CUST_REP) REFERENCES SALES_REPS(EMPL_NUМ) ON DELETE SET NULL
);

CREATE TABLE ORDERS( 
	ORDER_NUМ INT NOT NULL, 
	ORDER_DATE DATE NOT NULL , 
	CUST INT NOT NULL, 
	REP INT,
	MFR CHAR(3) NOT NULL, 
	PRODUCT CHAR(5) NOT NULL,
	QTY INT NOT NULL, 
	AМOUNT DECIMAL(9,2) NOT NULL, 
	PRIMARY KEY (ORDER_NUМ),
	CONSTRAINT PLACED_BY FOREIGN KEY (CUST) REFERENCES CUSTOMERS(CUST_NUМ) ON DELETE CASCADE,
	CONSTRAINT TAKEN_BY FOREIGN KEY (REP) REFERENCES SALES_REPS(EMPL_NUМ) ON DELETE SET NULL,
	CONSTRAINT IS_FOR FOREIGN KEY (MFR, PRODUCT) REFERENCES PRODUCTS(MFR_ID, PRODUCT_ID) ON DELETE RESTRICT
);
